name: Docker docs

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and run Docker image that builds docs
        run: |
          docker build --progress plain --tag docker-autodocs --build-arg GIT_ACCESS_TOKEN=${{ secrets.GIT_ACCESS_TOKEN }} --build-arg DATABASE_HOST_ARG=${{ secrets.DATABASE_HOST }} --build-arg DATABASE_USERNAME_ARG=${{ secrets.DATABASE_USERNAME }} --build-arg DATABASE_PASSWORD_ARG=${{ secrets.DATABASE_PASSWORD }} .
          npm run docker-docs:run
      - name: Upload docs html as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-docs-html
          path: output/index.html
      - name: Publish artifact to Cloudflare pages
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy output --project-name=dot-dapi-redocly
