name: Run dapi-lib tests

on:
  repository_dispatch:
    types: [trigger-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: dapi-lib

      - name: Run tests
        run: |
          npm run test