name: Run dapi-lib tests

on:
  repository_dispatch:
    types: [trigger-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          npm install
          npm run test
  publish-docs:
    uses: thencc/dapi-lib/.github/workflows/publish-docs.yaml@main